# Generated by Django 3.2.13 on 2023-06-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_num', models.CharField(max_length=150)),
                ('farm_name', models.CharField(max_length=150)),
                ('lat', models.CharField(max_length=150)),
                ('long', models.CharField(max_length=300)),
                ('distance', models.CharField(max_length=150)),
                ('result', models.CharField(max_length=150)),
            ],
        ),
    ]
